### ISSUE TITLE
[Q] AttributeError: 'ChannelPromise' object has no attribute '__value__'

### ISSUE THREAD

**Issue by abhishekrai43** [kaleidos-ventures/taiga-docker#78]
&gt; **READ THIS FIRST!**: We recently announced Taiga plans for the future and they greatly affect how we manage this repository and the current Taiga 6 release. Check it [here](https://blog.taiga.io/announcing_taiganext.html).chore: readme announce taiga-next

When running this application in a kubernetes cluster, I get the following error. I am not sure if kubernetes has anything to do with this though. Seems unlikely. I am not sure how to even begin to troubleshoot this. Any hints?
```
root@taiga-back-675fcdbd67-rx552:/taiga-back# ./manage.py createsuperuser
Username: testuser   
Email address: testuser@abc.com
Password:
Password (again):
Traceback (most recent call last):
  File "/opt/venv/lib/python3.7/site-packages/kombu/utils/functional.py", line 30, in __call__
    return self.__value__
AttributeError: 'ChannelPromise' object has no attribute '__value__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.7/site-packages/amqp/transport.py", line 173, in _connect
    host, port, family, socket.SOCK_STREAM, SOL_TCP)
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -5] No address associated with hostname
```

**Comment by abhishekrai43** [comment]
Are my ports wrong? which could be causing this?

```
kubernetes              ClusterIP      10.116.0.1      <none>          443/TCP          20h
taiga-async             ClusterIP      10.116.9.9      <none>          5672/TCP         20h
taiga-async-rabbitmq    ClusterIP      10.116.12.205   <none>          5672/TCP         20h
taiga-back              ClusterIP      10.116.14.31    <none>          8000/TCP         20h
taiga-db                ClusterIP      10.116.3.195    <none>          5432/TCP         20h
taiga-events            ClusterIP      10.116.3.44     <none>          8888/TCP         20h
taiga-events-rabbitmq   ClusterIP      10.116.6.162    <none>          5672/TCP         20h
taiga-front             LoadBalancer   10.116.8.252    34.72.101.154   9000:30825/TCP   20h
taiga-gateway           ClusterIP      10.116.6.68     <none>          9000/TCP         20h
```

**Comment by daniel-herrero** [comment]
It seems like a problem while connecting to Celery (the async worker). We would suggest you to to review your TAIGA ASYNC configuration, or even disable temporarily in order to give you more clues about it (`CELERY_ENABLED: "False"` in `docker-compose-init.yml`).

Sorry, but we can't assure that Kubernetes is not really involved (it's not a currently supported installation).

**Comment by abhishekrai43** [comment]
Did that ..getting the same error though. I have a feeling I am missing something at a basic level. I used Kompose to generate these files. If someone can have a look, that'd be great. 
https://github.com/abhishekrai43/kube-deploy/tree/taiga

**Comment by abhishekrai43** [comment]
It gives the same error. These are the files I am using. https://github.com/abhishekrai43/kube-deploy/tree/taiga

**Comment by abhishekrai43** [comment]
So, I got it to work...create the superuser I mean...CELER is enabled, Now I have Your username password is incorrect even though I am able to create a superuser.  All the pods are running. Probably shall create the cluster again and see

**Comment by abhishekrai43** [comment]
Tried pulling taiga-back:latest , 6.2, 6.4..Created the superuser....still getiing the username password is incorrect error.

**Comment by daniel-herrero** [comment]
In order to discard if it's either a Taiga or a Kubernete's problem you may perhaps simplify the problem performing a plain [Taiga Docker installation](https://docs.taiga.io/setup-production.html#setup-prod-with-docker) outside from Kubernetes, until you achieve to create the superuser, log in the application and perform the basic operations without errors.

Then, from a secure point you know for sure it's running properly, you can try to migrate that docker configuration to a Kubernetes cluster. This way you will probably discard any Taiga configuration issues, or get more support from community if you face any, and focus on the Kubernetes deployment.

**Comment by abhishekrai43** [comment]
Thanks for your reply. This "username/password is incorrect" I also faced when deploying the application in the regular fashion as well. I have a closed ticket for this. I was only able to solve it by importing the application from here https://github.com/taigaio/taiga-docker . There is another ticket open for this issue here labelled as a "Bug", however the discussion ended without a resolution..so seems unlikely this has to do with Kubernetes.

**Comment by abhishekrai43** [comment]
I understand Kubernetes is not supported , These are the files I am using. https://github.com/abhishekrai43/kube-deploy/tree/taiga . Leaving it here just in case someone is interested.

**Comment by abhishekrai43** [comment]
Going back to deploying this to VM.
